name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Configure SQL LocalDB
        shell: pwsh
        run: |
          $instance = "WeatherTest"
          sqllocaldb stop $instance 2>$null
          sqllocaldb delete $instance 2>$null
          sqllocaldb create $instance
          sqllocaldb start $instance
          $connectionString = "Server=(localdb)\$instance;Database=master;Integrated Security=true;TrustServerCertificate=True"
          Add-Content -Path $env:GITHUB_ENV -Value "SQL_CONNECTION_STRING=$connectionString"
      - name: Download NuGet
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "nuget.exe"
      - name: Restore packages
        shell: pwsh
        run: |
          .\nuget.exe install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory packages
      - name: Build
        shell: pwsh
        run: |
          dotnet build Weather.sln
      - name: Test
        shell: pwsh
        run: |
         dotnet test
