name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      SQL_CONNECTION_STRING: "Server=(localdb)\\WeatherLocalDb;Database=WeatherTest;Integrated Security=true;TrustServerCertificate=True"
    steps:
      - uses: actions/checkout@v4
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Prepare LocalDB
        shell: pwsh
        run: |
          sqllocaldb create WeatherLocalDb -s
          sqlcmd -S "(localdb)\WeatherLocalDb" -Q "IF DB_ID('WeatherTest') IS NULL CREATE DATABASE WeatherTest;"
      - name: Restore packages
        shell: pwsh
        run: |
          nuget restore Weather.sln
          nuget install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory packages
      - name: Build
        shell: pwsh
        run: |
          msbuild Weather.sln /p:Configuration=Debug
      - name: Test
        shell: pwsh
        run: |
          .\packages\NUnit.ConsoleRunner.3.17.0\tools\nunit3-console.exe .\tests\Weather.Api.Tests\bin\Debug\Weather.Api.Tests.dll
