name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "YourStrong!Passw0rd"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1'"
          --health-interval 10s --health-timeout 5s --health-retries 10
    env:
      SQL_CONNECTION_STRING: "Server=localhost,1433;Database=master;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel
      - name: Install NuGet
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
      - name: Restore packages
        run: |
          mono nuget.exe restore Weather.sln
          mono nuget.exe install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory packages
      - name: Build
        run: |
          xbuild Weather.sln
      - name: Test
        run: |
          mono packages/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe WeatherApi.Tests/bin/Debug/WeatherApi.Tests.dll --framework=mono-4.0
