name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mono
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-devel
      - name: Install NuGet
        run: |
          curl -L https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe
      - name: Restore packages
        run: |
          mono nuget.exe restore Weather.sln
          mono nuget.exe install NUnit.ConsoleRunner -Version 3.17.0 -OutputDirectory packages
      - name: Build
        run: |
          xbuild Weather.sln
      - name: Test
        run: |
          mono packages/NUnit.ConsoleRunner.3.17.0/tools/nunit3-console.exe WeatherApi.Tests/bin/Debug/WeatherApi.Tests.dll --framework=mono-4.0
